build:
    cargo build --release --target wasm32-unknown-unknown
    wasm-opt -O4 target/wasm32-unknown-unknown/release/ud-nft.wasm -o ud-nft.wasm

decompile:
    wasm2wat --generate-names target/wasm32-unknown-unknown/release/ud-nft.wasm