build:
    just -f erc20/justfile build
    just -f ud-nft/justfile build
    mkdir -p contracts
    mv erc20/udtoken.wasm contracts
    mv ud-nft/ud-nft.wasm contracts

prepare:
	rustup target add wasm32-unknown-unknown

build-contract:
	cargo build --release -p cep47 --target wasm32-unknown-unknown
	wasm-strip target/wasm32-unknown-unknown/release/cep47-token.wasm 2>/dev/null | true

build-contract-market:
	cargo build --release -p contract-market --target wasm32-unknown-unknown
	wasm-strip target/wasm32-unknown-unknown/release/contract-market.wasm 2>/dev/null | true

test-only:
	cargo test -p tests

copy-wasm-file-to-test:
	cp target/wasm32-unknown-unknown/release/*.wasm tests/wasm

build-all: build-contract build-contract-market copy-wasm-file-to-test

test: build-contract build-contract-market copy-wasm-file-to-test test-only

clippy:
	cargo clippy --all-targets --all -- -D warnings

check-lint: clippy
	cargo fmt --all -- --check

lint: clippy
	cargo fmt --all

clean:
	cargo clean
	rm -rf tests/wasm/*.wasm